version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-broker
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - logistics-net

networks:
  logistics-net:
    driver: bridge